dev:
 postgres:
   url: "jdbc:postgresql://localhost:5432/postgres"
   user: "postgres"
   password: "Iphone9@"
   driver: "org.postgresql.Driver"
   port: 5432

 oracle:
   username: "test123"
   password: "oracle_password"
   connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"


qa:
 postgres:
   url: "jdbc:postgresql://localhost:5432/postgres"
   user: "postgres"
   password: "Iphone9@"
   driver: "org.postgresql.Driver"
   port: 5432

 snowflake:
   url: "jdbc:snowflake://JIOHBRN-VO25590.snowflakecomputing.com"
   user: "SHREE"
   password: "ShivajiShree@99"
   database: 'SNOWFLAKE_LEARNING_DB'
   schema: 'INFORMATION_SCHEMA'
   dbtable: 'APPLICABLE_ROLES'
   driver: "net.snowflake.client.jdbc.SnowflakeDriver"

 adls:
   adls_account_name: "decauto21"
   adls_container_name: "test"
   key: "9Gn7n0tlNXAi7cImLo2zM375TWtCeWYFhJa+vcEXz6/MAgJcNTPn9xzC44EiwfFOnYZkQ1IrEajO+AStFp8xDQ=="  # Your Account Key#my adls accout#





 #sqlserver:
#    url: "jdbc:sqlserver://decserver.database.windows.net:1433;database=decauto" #Sreenis azure sql server details
#    user: "decadmin"
#    password: "Dharmavaram1@"
#    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

prod:
 postgres:
   url: "jdbc:postgresql://localhost:5432/postgres"
   user: "postgres"
   password: "Iphone9@"
   driver: "org.postgresql.Driver"
   port: 5432
 oracle:
   username: "oracle_user"
   password: "oracle_password"
   connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"
